# OpenTelemetry Collector Configuration for OTEL-Only Logging
# Fortium External Metrics Web Service

receivers:
  # OTLP receiver for logs, traces, and metrics
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://localhost:3000"
            - "http://localhost:3001"
          allowed_headers:
            - "*"

  # Prometheus receiver for collector metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8888']

processors:
  # Batch processor for efficient data transmission
  batch:
    timeout: 10s
    send_batch_size: 1024
    send_batch_max_size: 2048

  # Memory limiter to prevent OOM
  memory_limiter:
    limit_mib: 512

  # Resource processor to add resource attributes
  resource:
    attributes:
      - key: service.environment
        value: otel-only
        action: upsert
      - key: collector.name
        value: fortium-otel-collector
        action: upsert
      - key: collector.version
        value: 1.0.0
        action: upsert

  # Attributes processor for log enhancement
  attributes/logs:
    actions:
      - key: fortium.platform
        value: external-metrics
        action: upsert
      - key: log.source
        value: otel-collector
        action: upsert
      - key: environment
        value: otel-only
        action: upsert

  # Filter processor to remove sensitive data
  filter/logs:
    logs:
      exclude:
        match_type: regexp
        bodies:
          - "password"
          - "secret"
          - "token"
          - "api_key"

exporters:
  # Logging exporter for development/debugging
  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 200

  # OTLP exporter to Jaeger for traces
  otlp/jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  # Prometheus exporter for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: fortium_metrics
    const_labels:
      environment: otel-only

  # File exporter for logs (backup)
  file/logs:
    path: /tmp/otel-logs.json
    rotation:
      max_megabytes: 100
      max_days: 7
      max_backups: 10

service:
  # Pipeline configuration
  pipelines:
    # Logs pipeline
    logs:
      receivers: [otlp]
      processors:
        - memory_limiter
        - resource
        - attributes/logs
        - filter/logs
        - batch
      exporters: [logging, file/logs]

    # Traces pipeline
    traces:
      receivers: [otlp]
      processors:
        - memory_limiter
        - resource
        - batch
      exporters: [logging, otlp/jaeger]

    # Metrics pipeline
    metrics:
      receivers: [otlp, prometheus]
      processors:
        - memory_limiter
        - resource
        - batch
      exporters: [logging, prometheus]

  # Extensions for health checks and monitoring
  extensions: [health_check, pprof, zpages]

extensions:
  # Health check extension
  health_check:
    endpoint: 0.0.0.0:13133

  # Performance profiling
  pprof:
    endpoint: 0.0.0.0:1777

  # Z-Pages for debugging
  zpages:
    endpoint: 0.0.0.0:55679

# Telemetry configuration
telemetry:
  logs:
    level: info
    development: false
    sampling:
      initial: 5
      thereafter: 200
  metrics:
    level: basic
    address: 0.0.0.0:8888