[project]
name = "claude-config"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cchooks>=0.1.4",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "psutil>=5.9.0",
]
