{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with (include "chart.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: {{ .Values.secret.type | default "Opaque" }}
{{- if .Values.secret.data }}
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if .Values.secret.stringData }}
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- if .Values.secret.extraSecrets }}
{{- range $name, $secret := .Values.secret.extraSecrets }}
{{- if $secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" $ }}-{{ $name }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  {{- with (include "chart.annotations" $) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: {{ $secret.type | default "Opaque" }}
{{- if $secret.data }}
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if $secret.stringData }}
stringData:
  {{- range $key, $value := $secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
---
{{- if and .Values.ingress.enabled .Values.ingress.tls .Values.ingress.generateTLSSecret }}
{{- range .Values.ingress.tls }}
{{- if not .existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: tls
  {{- with (include "chart.annotations" $) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  {{- include "chart.gen-certs" $ | nindent 2 }}
---
{{- end }}
{{- end }}
{{- end }}