{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.serviceAccountName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- $annotations := include "chart.annotations" . }}
  {{- if or $annotations .Values.serviceAccount.annotations }}
  annotations:
    {{- if $annotations }}
    {{- $annotations | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- if .Values.serviceAccount.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- else }}
automountServiceAccountToken: false
{{- end }}
{{- if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.serviceAccount.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
{{- if .Values.serviceAccount.secrets }}
secrets:
  {{- range .Values.serviceAccount.secrets }}
  - name: {{ .name }}
  {{- end }}
{{- end }}
{{- end }}