# Fly.io Configuration for Rails API
app = "rails-api"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "bin/rails db:migrate"

[env]
  RAILS_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/up"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
