# OpenTelemetry Collector OpAMP Configuration
# Remote configuration management for SignOz collector

server:
  server_endpoint: http://query-service:8080/api/v1/opamp
  
client:
  instanceId: "${HOSTNAME:-signoz-otel-collector}"
  agentDescription:
    identifyingAttributes:
      - key: service.name
        value: signoz-otel-collector
      - key: service.version
        value: 0.111.16
    nonIdentifyingAttributes:
      - key: deployment.environment
        value: docker