apiVersion: v2
name: monitoring-web-service
description: External Metrics Web Service - A comprehensive monitoring and metrics collection platform with PostgreSQL/TimescaleDB backend
type: application
version: 1.0.0
appVersion: "1.0.0"

# Maintainer information
maintainers:
  - name: Fortium Infrastructure Team
    email: infrastructure@fortium.dev
    url: https://github.com/FortiumPartners

# Keywords for chart discovery
keywords:
  - monitoring
  - metrics
  - timeseries
  - postgresql
  - timescaledb
  - external-metrics
  - observability

# Home and source URLs
home: https://github.com/FortiumPartners/monitoring-web-service
sources:
  - https://github.com/FortiumPartners/monitoring-web-service

# Chart annotations
annotations:
  category: Monitoring
  licenses: MIT
  images: |
    - name: monitoring-web-service
      image: fortium-metrics-web-service:1.0.0
    - name: postgresql
      image: timescale/timescaledb:latest-pg14
    - name: redis
      image: redis:7-alpine
    - name: postgres-exporter
      image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0

# Dependencies (sub-charts)
dependencies:
  - name: postgresql
    version: "^12.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
    tags:
      - database
  - name: redis
    version: "^18.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    tags:
      - cache
  - name: prometheus
    version: "^25.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
    tags:
      - monitoring
  - name: grafana
    version: "^7.0.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled
    tags:
      - monitoring