# Fly.io Configuration for Flask + Redis Application
app = "flask-redis"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_APP = "app.py"
  FLASK_ENV = "production"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
