# Fly.io Configuration for Static Site
app = "static-site"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0  # Scale to zero when no traffic

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
