{{/*
External Metrics Web Service - ConfigMap Template
*/}}
{{- if .Values.configMap.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring-web-service.fullname" . }}
  labels:
    {{- include "monitoring-web-service.labels" . | nindent 4 }}
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}