{{/*
External Metrics Web Service - NetworkPolicy Template
*/}}
{{- if .Values.networkPolicy.enabled }}
apiVersion: {{ include "monitoring-web-service.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "monitoring-web-service.fullname" . }}
  labels:
    {{- include "monitoring-web-service.labels" . | nindent 4 }}
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "monitoring-web-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- range .Values.networkPolicy.ingress }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- range .Values.networkPolicy.egress }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}