{{/*
External Metrics Web Service - PodDisruptionBudget Template
*/}}
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "monitoring-web-service.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "monitoring-web-service.fullname" . }}
  labels:
    {{- include "monitoring-web-service.labels" . | nindent 4 }}
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "monitoring-web-service.selectorLabels" . | nindent 6 }}
{{- end }}