# Fly.io Configuration for Phoenix LiveView
app = "phoenix-liveview"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "phoenix-liveview.fly.dev"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
