# Fly.io Configuration for Django Application
# https://fly.io/docs/reference/configuration/

app = "django-web"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

[env]
  DJANGO_SETTINGS_MODULE = "config.settings.production"
  PORT = "8000"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health/"

[processes]
  web = "gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 4 --timeout 60 --access-logfile - --error-logfile -"
  worker = "celery -A config worker -l info"

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static/"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 512
